### ISSUE TITLE
official name is "Jira".

### ISSUE THREAD

**Issue by mihirogi** [co6ted/co6ted.github.io#1]
There are two types of "JIRA": "Jira Core" and "Jira Software".
Users do not distinguish between them and call them "Jira" or "JIRA".
If you want to call it "Jira", the official name is "Jira".
It is not "JIRA".

![image](https://user-images.githubusercontent.com/23702467/103056290-e4962200-45df-11eb-9ea9-f324072e3765.png)

**Comment by co6ted** [comment]
Thanks @mihirogi, fixed JIRA to Jira as you pointed out.
